---
- name: Import tasks from setup-ovs.yml
  ansible.builtin.import_tasks: setup-ovs.yml
- name: Import tasks from config.yml
  ansible.builtin.import_tasks: config.yml
- name: Import tasks from check-containers.yml
  ansible.builtin.import_tasks: check-containers.yml
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
